const mongoose = require('mongoose')
const db1 = require('../config/key').mongoUsersURI;
const db2 = require('../config/key').mongoLevelsURI;
const db3 = require('../config/key').mongoTricksURI;
const db4 = require('../config/key').mongoLevels2URI;
const db5 = require('../config/key').mongoLevels3URI;
const db6 = require('../config/key').mongoLevels4URI;
const db7 = require('../config/key').mongoLevels5URI;
const db8 = require('../config/key').mongoLevels6URI;
const users = mongoose.createConnection(db1,{ useNewUrlParser: true });
const levels = mongoose.createConnection(db2,{ useNewUrlParser: true });
const levels2 = mongoose.createConnection(db4,{ useNewUrlParser: true });
const levels3 = mongoose.createConnection(db5,{ useNewUrlParser: true });
const levels4 = mongoose.createConnection(db6,{ useNewUrlParser: true });
const levels5 = mongoose.createConnection(db7,{ useNewUrlParser: true });
const levels6 = mongoose.createConnection(db8,{ useNewUrlParser: true });
const tricks = mongoose.createConnection(db3,{ useNewUrlParser: true });

module.exports = {users,levels,tricks,levels2,levels3,levels4,levels5,levels6};